import axios from 'axios'
import Head from 'next/head'
import { useState, FormEvent } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [ url, setUrl ] = useState('')

  async function handleRequest(event: FormEvent) {
    event.preventDefault()

    const response = await axios.post(url)

    console.log(response)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Request App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>Digite a url que deseja fazer a requisição do tipo post: </h1>

        <form onClick={handleRequest} className={styles.formContainer}>
          <input 
            className={styles.inputMain}
            type="text"
            onChange={event => setUrl(event.target.value)}
            value={url}
          />

          <button type="submit" className={styles.button}>
            Enviar
          </button>
        </form>
      </main>
    </div>
  )
}
